
# specify as
# name: available sequences as present in
#
#   constants.filenames.optional_images

datasets:
  ADNI:   [T1]
  ADNI3:  [T1, FLAIR]
  AIBL:   [T1, T2, FLAIR]
  HCP:    [T1, T2]
  OASIS3: [T1, CT]

  HCP: [] # [T1]
  WH2015: [PD] # [T1, PD]
