name: brainnet
channels:
  - conda-forge
dependencies:
  - python = 3.11
  # nvcc compiler
  - cuda-toolkit = 12.4
  - nibabel
  - ninja
  - numpy
  - pip
  # for brainsynth
  - scipy >= 1.11
  - scikit-learn >= 1.3
  - pip:
    - torch == 2.6
    # seems to be more up to date
    - wandb
