body:
  model: UNet
  kwargs:
    spatial_dims: 3
    in_channels: 1
    encoder_channels: [[32], [64], [128]]
    decoder_channels: [[64], [32]]
    # encoder_features: [[False], [False], [False]]
    # decoder_features: [[False], [True]]

heads:
  surface:
    module:
      name: SurfaceAdjustModule
      kwargs:
        surfaces: [white, pial]
        resolution: 5
        channels: [32]
        n_iterations: 10
