feature_extractor:
  model: UNet
  kwargs:
    spatial_dims: 3
    in_channels: 1
    out_channels: 64
    channels: [64, 128, 256, 512]
    strides: [2, 2, 2] # len(channels) - 1 entries
tasks:
  segmentation:
    module: SegmentationModule
    module_kwargs:
      out_channels: 33
