functions:

  white:
    edge:
      module:
        name: SurfaceRegularizationLoss
        kwargs:
          y_pred: white
      loss:
        name: brainnet.modules.losses.EdgeLengthVarianceLoss

    chamfer:
      module:
        name: SurfaceSupervisedLoss
        kwargs:
          y_pred: white
          y_true: white
      loss:
        name: brainnet.modules.losses.SymmetricChamferLoss

    curv:
      module:
        name: SurfaceSupervisedLoss
        kwargs:
          y_pred: white
          y_true: white
      loss:
        name: brainnet.modules.losses.SymmetricCurvatureNormLoss

  pial:
    edge:
      module:
        name: SurfaceRegularizationLoss
        kwargs:
          y_pred: pial
      loss:
        name: brainnet.modules.losses.EdgeLengthVarianceLoss

    chamfer:
      module:
        name: SurfaceSupervisedLoss
        kwargs:
          y_pred: pial
          y_true: pial
      loss:
        name: brainnet.modules.losses.SymmetricChamferLoss

    curv:
      module:
        name: SurfaceSupervisedLoss
        kwargs:
          y_pred: pial
          y_true: pial
      loss:
        name: brainnet.modules.losses.SymmetricCurvatureNormLoss

  # cross:
  #   thickness:
  #     module:
  #       name: SurfaceSupervisedLoss
  #       kwargs:
  #         y_pred: null # pass white *and* pial
  #         y_true: null # pass white *and* pial
  #     loss:
  #       name: brainnet.modules.losses.SymmetricThicknessLoss


head_weights:
  white: 1.0
  pial: 1.0
  # cross: 1.0

loss_weights:
  white:
    edge:         1.0
    chamfer:      1.0
    curv:        10.0

  pial:
    edge:         1.0
    chamfer:      1.0
    curv:         5.0

  # cross:
  #   thickness: 1.0
